/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eazy_mng;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudip Maiti
 */
public class CHANGE_PASS_MAN extends javax.swing.JFrame {
    
   String time = null;
     String date = null;
     String ph = null;
     String Name;
     String Id = null;
     String emll = null;
     String otp;
     String a;
     String b;
     String c;
     int mng_Id;
     String mng ;
     String msc;
    /**
     * Creates new form CHANGE_PASS_MAN
     */
    public CHANGE_PASS_MAN() {
        initComponents();
        // pass1.setEditable(false);
                 
       //  b.setEnabled(false);
     //   get_otp.setEnabled(true);
    }
    void change (String fullname, String mng_Id,String email,String t1,String d1,String p) {
        time = t1;
        date = d1;
        Name = fullname;
        ph= p;
        emll=email;
        mng_name.setText(fullname);
        System.out.println("fullnamegggggg" + fullname);
        mng_id.setText(mng_Id);
        Id = mng_Id;
        System.out.println("mng_Idhhhhhhhhh " + mng_Id);
        eml.setText(email);
        System.out.println("emailjjjjjjj" + email );
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mng_name = new javax.swing.JLabel();
        get_otp = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        Close_bb = new javax.swing.JPanel();
        Close_b = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eml = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mng_id = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mng_name.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        mng_name.setForeground(new java.awt.Color(0, 204, 102));
        mng_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(mng_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 420, 40));

        get_otp.setBackground(new java.awt.Color(255, 255, 255));
        get_otp.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        get_otp.setForeground(new java.awt.Color(0, 0, 0));
        get_otp.setText("Get OTP");
        get_otp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_otpMouseClicked(evt);
            }
        });
        get_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_otpActionPerformed(evt);
            }
        });
        jPanel1.add(get_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 200, 40));

        pass.setBackground(new java.awt.Color(204, 255, 204));
        pass.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 204, 102));
        pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pass.setText("Enter Current Password");
        pass.setToolTipText("Enter Your Old Password");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 102)));
        pass.setPreferredSize(new java.awt.Dimension(420, 40));
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 390, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close_bb.setBackground(new java.awt.Color(0, 204, 102));
        Close_bb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_bbMouseClicked(evt);
            }
        });

        Close_b.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        Close_b.setForeground(new java.awt.Color(255, 255, 255));
        Close_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_b.setText("×");
        Close_b.setPreferredSize(new java.awt.Dimension(40, 40));
        Close_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_bMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Close_bbLayout = new javax.swing.GroupLayout(Close_bb);
        Close_bb.setLayout(Close_bbLayout);
        Close_bbLayout.setHorizontalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Close_bbLayout.setVerticalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Close_bbLayout.createSequentialGroup()
                .addComponent(Close_b, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(Close_bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PASSWORD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Name.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email_a.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        eml.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        eml.setForeground(new java.awt.Color(0, 204, 102));
        eml.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eml.setText(" ");
        jPanel1.add(eml, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 420, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/key_1.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        mng_id.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        mng_id.setForeground(new java.awt.Color(0, 204, 102));
        mng_id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 420, 40));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        open.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (2).png"))); // NOI18N
        open.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 102)));
        open.setPreferredSize(new java.awt.Dimension(24, 33));
        open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openMousePressed(evt);
            }
        });
        jPanel1.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 40, 40));

        hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (1).png"))); // NOI18N
        hide.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 102)));
        hide.setPreferredSize(new java.awt.Dimension(24, 33));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
        });
        jPanel1.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(570, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
         if(pass.getText().equals("Enter Current Password")){
            
            pass.setText("");
            pass.setEchoChar('*');
            pass.setForeground(new Color(0,204,102));
        }
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
         if(pass.getText().equals("")){
           
            pass.setText("Enter Current Password");
            pass.setEchoChar((char)0);
            pass.setForeground(new Color(128,128,128));
        }else{
            pass.setVisible(true);
        }
    }//GEN-LAST:event_passFocusLost

    private void openMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMousePressed
        // TODO add your handling code here:
        hide.setVisible(true);
        open.setVisible(false);
        pass.setEchoChar('*');
    }//GEN-LAST:event_openMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        // TODO add your handling code here:
        open.setVisible(true);
        hide.setVisible(false);
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_hideMousePressed

    private void Close_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseClicked
        // TODO add your handling code here:
        DASHBOARD_M dm = new DASHBOARD_M ();
         String Name =mng_name.getText();
         String Id = mng_id.getText();
         String emll = eml.getText();
         //String fullname, String mng_Id,String email, String phone, String Date, String Time
        dm.mngname(Name,Id,emll,ph,date,time);
        System.out.println("skjdfjksdfkl"+ time);
        System.out.println("dddddddd"+date);
        dm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close_bMouseClicked

    private void Close_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseEntered
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(228, 0, 23));
        Close_b.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Close_bMouseEntered

    private void Close_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseExited
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(255, 255, 255));
        Close_b.setForeground(new Color(14,73,181));
    }//GEN-LAST:event_Close_bMouseExited

    private void Close_bbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bbMouseClicked
        // TODO add your handling code here:
        DASHBOARD_M dm = new DASHBOARD_M();
        dm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Close_bbMouseClicked

    private void get_otpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_otpMouseClicked
                      
    }//GEN-LAST:event_get_otpMouseClicked

    private void get_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_otpActionPerformed
        // TODO add your handling code here:
        String p_email = mng_id.getText();
        String p_pass = pass.getText();
        
        //String mng_Id = null;
        String eml= null;
        String passw= null;
        
        try {
            //  Data fetch from database
            String sql = "Select * from register Where MNG_ID = ? ";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,p_email);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                eml =rs.getString("Email");
                passw =rs.getString("PASSWORD");
                System.out.println("EMAILLLLLLLL "+eml);
                System.out.println("MNGGGGGGGGGGGGG "+p_email);
                System.out.println("Passssssss "+passw);
                rs.close();
                ps.close();
            
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
        try{
           
            if(p_pass.equals("")){
                JOptionPane.showMessageDialog(this, "At first Enter Your Password ");
            }else if(REGISTRATION_DATAOBEJECT.validate(p_email, p_pass)){
                gen_otp();
              }else{
                
                JOptionPane.showMessageDialog(null,"Enter Correct Password", "Login Error", JOptionPane.ERROR_MESSAGE);
                 
                 get_otp.setEnabled(true);
            }
        }catch (Exception e){
            System.out.println("Exception -"+e);
        }  
    }//GEN-LAST:event_get_otpActionPerformed
  
    
   public void gen_otp(){
        Random rand = new Random();
        otp = String.format("%06d",rand.nextInt(1000000));
        System.out.println("YOUR OTP IS "+otp);
                 
               mng = eml.getText();
               msc= "YOUR OTP IS "+otp;
            MAIL.send(mng,"Welcome"+" "+Name, msc);
            JOptionPane.showMessageDialog(null, "OTP Send To "+" "+Name+" " +"By Email");
        
        a= JOptionPane.showInputDialog(this,"Enter Your OTP");
                 if (a.equals(otp)){
            
                     JOptionPane.showMessageDialog(null, "OTP Match");
                       CHANGE_PASS_MAN_1 cpm = new CHANGE_PASS_MAN_1(); 
                        cpm.cpmm(Name, Id, emll, time, date, ph);
                         cpm.setVisible(true);              
                         this.dispose();
                 }else {
                     JOptionPane.showMessageDialog(null, "OTP Not Match. Only 2 try Left!");
                  b = JOptionPane.showInputDialog(this,"Enter Your OTP");
                 }if(b.equals(otp)){
                     
                             JOptionPane.showMessageDialog(null, "OTP Match");
                                CHANGE_PASS_MAN_1 cpm = new CHANGE_PASS_MAN_1(); 
                                 cpm.cpmm(Name, Id, emll, time, date, ph);
                                  cpm.setVisible(true);              
                                 this.dispose();
                  } else {
                     JOptionPane.showMessageDialog(null, "OTP Not Match. Only 1 try Left!");
                     c = JOptionPane.showInputDialog(this,"Enter Your OTP");
                 }if(c.equals(otp)){
                        
                             JOptionPane.showMessageDialog(null, "OTP Match");
                                CHANGE_PASS_MAN_1 cpm = new CHANGE_PASS_MAN_1(); 
                                 cpm.cpmm(Name, Id, emll, time, date, ph);
                                  cpm.setVisible(true);              
                                 this.dispose();
                                         
                      }else{
                          JOptionPane.showMessageDialog(null, "You estimate 3 attempts on OTP verification! Please, try again after some time.Thank You!");
                      }
                      
                 
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS_MAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS_MAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS_MAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS_MAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHANGE_PASS_MAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_b;
    private javax.swing.JPanel Close_bb;
    private javax.swing.JLabel eml;
    private javax.swing.JButton get_otp;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mng_id;
    private javax.swing.JLabel mng_name;
    private javax.swing.JLabel open;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
