/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eazy_mng;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Sudip Maiti
 */
public class DAILY_REPORT extends javax.swing.JFrame {
String Dd;
    String ID = null;
    String Name = null;
    String Phone = null;
    String Email = null;
   
   
    String date=null;
    String time = null;
    /**
     * Creates new form DAILY_REPORT
     */
    public DAILY_REPORT() {
        initComponents();
        date();
        time();
        ssel.setVisible(false);
        ppur.setVisible(false);
        Pur.setVisible(false);
        alll.setVisible(true);
        sell.setVisible(false);
        All.setVisible(true);
        
        Dd=dd.getText();
        cc1();
    }
     void drr (String fullname, String mng_Id,String email,String t1,String d1,String p) {
       Name = fullname;
        ID = mng_Id;
        Email = email;
        time = t1;
        date = d1;
        Phone= p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        sell = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        alll = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        Pur = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ssel = new javax.swing.JPanel();
        Paaaa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Taa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EMPP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PII = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t0 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EMPII = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ppro_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        QQW = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        d0 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        pfff = new javax.swing.JTextField();
        ppur = new javax.swing.JPanel();
        ppro_id1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        scost = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cata = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uprice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Pronaa1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        qun1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        d5 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        mnii = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        mnamee = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        TOTALL = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        All = new javax.swing.JPanel();
        Status = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ttt1 = new javax.swing.JTextField();
        Pric = new javax.swing.JTextField();
        qqt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        piid = new javax.swing.JTextField();
        vvname = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ddd1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        pnnam = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        TOTALL1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DAILY REPORT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1054, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(432, 432, 432)
                    .addComponent(jLabel21)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        jPanel6.setBackground(new java.awt.Color(109, 220, 207));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Purchase & Sell Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Go");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 64, 2), 1, true));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, 40));

        jPanel4.setBackground(new java.awt.Color(109, 220, 207));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r1.setBackground(new java.awt.Color(109, 220, 207));
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        r1.setForeground(new java.awt.Color(0, 0, 204));
        r1.setText("All");
        r1.setToolTipText("");
        jPanel4.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        r3.setBackground(new java.awt.Color(109, 220, 207));
        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        r3.setForeground(new java.awt.Color(0, 0, 204));
        r3.setText("Sell");
        r3.setToolTipText("");
        jPanel4.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 14, 61, 30));

        r2.setBackground(new java.awt.Color(109, 220, 207));
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        r2.setForeground(new java.awt.Color(0, 0, 204));
        r2.setText("Purchase");
        r2.setToolTipText("");
        jPanel4.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 13, -1, 30));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 310, 50));

        sell.setBackground(new java.awt.Color(109, 220, 207));
        sell.setForeground(new java.awt.Color(232, 69, 69));

        table4.setBackground(new java.awt.Color(192, 192, 255));
        table4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        table4.setForeground(new java.awt.Color(0, 0, 0));
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Quantity ", "Price", "Total", "Profit", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table4);

        javax.swing.GroupLayout sellLayout = new javax.swing.GroupLayout(sell);
        sell.setLayout(sellLayout);
        sellLayout.setHorizontalGroup(
            sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sellLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)))
        );
        sellLayout.setVerticalGroup(
            sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
            .addGroup(sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 220));

        alll.setBackground(new java.awt.Color(109, 220, 207));

        table3.setBackground(new java.awt.Color(192, 192, 255));
        table3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        table3.setForeground(new java.awt.Color(0, 0, 0));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Date", "Time", "Vendor Name", "Product Id", "Product Name", "Price", "Quantity ", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        javax.swing.GroupLayout alllLayout = new javax.swing.GroupLayout(alll);
        alll.setLayout(alllLayout);
        alllLayout.setHorizontalGroup(
            alllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE))
        );
        alllLayout.setVerticalGroup(
            alllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(alll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 220));

        Pur.setBackground(new java.awt.Color(109, 220, 207));

        table2.setBackground(new java.awt.Color(192, 192, 255));
        table2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        table2.setForeground(new java.awt.Color(0, 0, 0));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Quantity ", "Price", "Total", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        javax.swing.GroupLayout PurLayout = new javax.swing.GroupLayout(Pur);
        Pur.setLayout(PurLayout);
        PurLayout.setHorizontalGroup(
            PurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE))
        );
        PurLayout.setVerticalGroup(
            PurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(Pur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 220));

        search.setBackground(new java.awt.Color(109, 220, 207));
        search.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 0, 0));
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setText("-: Enter Product Id :-");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 204)));
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel6.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circular-arrow.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 153)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 36, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search11.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 204)));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 36, 30, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1010, 310));

        ssel.setBackground(new java.awt.Color(143, 206, 254));
        ssel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2), "Sell Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N
        ssel.setLayout(null);

        Paaaa.setBackground(new java.awt.Color(255, 255, 255));
        Paaaa.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Paaaa.setForeground(new java.awt.Color(0, 0, 204));
        Paaaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(Paaaa);
        Paaaa.setBounds(370, 40, 270, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("Product Name");
        ssel.add(jLabel9);
        jLabel9.setBounds(370, 20, 81, 20);

        Taa.setBackground(new java.awt.Color(255, 255, 255));
        Taa.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Taa.setForeground(new java.awt.Color(0, 0, 204));
        Taa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(Taa);
        Taa.setBounds(370, 90, 270, 20);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 51));
        jLabel14.setText("Total :");
        ssel.add(jLabel14);
        jLabel14.setBounds(370, 70, 140, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Employee Name :");
        ssel.add(jLabel4);
        jLabel4.setBounds(370, 120, 120, 20);

        EMPP.setBackground(new java.awt.Color(255, 255, 255));
        EMPP.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        EMPP.setForeground(new java.awt.Color(0, 0, 204));
        EMPP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(EMPP);
        EMPP.setBounds(370, 140, 270, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 51));
        jLabel12.setText("Price");
        ssel.add(jLabel12);
        jLabel12.setBounds(40, 70, 110, 20);

        PII.setBackground(new java.awt.Color(255, 255, 255));
        PII.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        PII.setForeground(new java.awt.Color(0, 0, 204));
        PII.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(PII);
        PII.setBounds(40, 90, 270, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setText("Profit :");
        ssel.add(jLabel10);
        jLabel10.setBounds(710, 70, 140, 20);

        t0.setBackground(new java.awt.Color(255, 255, 255));
        t0.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        t0.setForeground(new java.awt.Color(0, 0, 204));
        t0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(t0);
        t0.setBounds(860, 140, 110, 20);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("Time :");
        ssel.add(jLabel11);
        jLabel11.setBounds(860, 120, 40, 20);

        EMPII.setBackground(new java.awt.Color(255, 255, 255));
        EMPII.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        EMPII.setForeground(new java.awt.Color(0, 0, 204));
        EMPII.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(EMPII);
        EMPII.setBounds(40, 140, 270, 20);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 51));
        jLabel13.setText("Product ID");
        ssel.add(jLabel13);
        jLabel13.setBounds(40, 20, 70, 20);

        ppro_id.setBackground(new java.awt.Color(255, 255, 255));
        ppro_id.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ppro_id.setForeground(new java.awt.Color(0, 0, 204));
        ppro_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(ppro_id);
        ppro_id.setBounds(40, 40, 270, 20);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 51));
        jLabel15.setText("Employee ID :");
        ssel.add(jLabel15);
        jLabel15.setBounds(40, 120, 130, 20);

        QQW.setBackground(new java.awt.Color(255, 255, 255));
        QQW.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        QQW.setForeground(new java.awt.Color(0, 0, 204));
        QQW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(QQW);
        QQW.setBounds(710, 40, 260, 20);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("Quantity :");
        ssel.add(jLabel31);
        jLabel31.setBounds(710, 20, 53, 20);

        d0.setBackground(new java.awt.Color(255, 255, 255));
        d0.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        d0.setForeground(new java.awt.Color(0, 0, 204));
        d0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ssel.add(d0);
        d0.setBounds(710, 140, 120, 20);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 51));
        jLabel32.setText("Date :");
        ssel.add(jLabel32);
        jLabel32.setBounds(710, 120, 40, 20);

        pfff.setBackground(new java.awt.Color(255, 255, 255));
        pfff.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        pfff.setForeground(new java.awt.Color(0, 0, 204));
        pfff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pfff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfffActionPerformed(evt);
            }
        });
        ssel.add(pfff);
        pfff.setBounds(710, 90, 260, 20);

        jPanel1.add(ssel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1010, 190));

        ppur.setBackground(new java.awt.Color(143, 206, 254));
        ppur.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2), "Purches Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N
        ppur.setLayout(null);

        ppro_id1.setBackground(new java.awt.Color(255, 255, 255));
        ppro_id1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ppro_id1.setForeground(new java.awt.Color(0, 0, 204));
        ppro_id1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppro_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppro_id1ActionPerformed(evt);
            }
        });
        ppur.add(ppro_id1);
        ppro_id1.setBounds(40, 40, 270, 20);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Product ID :");
        ppur.add(jLabel19);
        jLabel19.setBounds(40, 20, 70, 20);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Standard Cast :");
        ppur.add(jLabel25);
        jLabel25.setBounds(40, 60, 110, 20);

        scost.setBackground(new java.awt.Color(255, 255, 255));
        scost.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        scost.setForeground(new java.awt.Color(0, 0, 204));
        scost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(scost);
        scost.setBounds(40, 80, 270, 20);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Manager ID :");
        ppur.add(jLabel26);
        jLabel26.setBounds(40, 140, 130, 20);

        cata.setBackground(new java.awt.Color(255, 255, 255));
        cata.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cata.setForeground(new java.awt.Color(0, 0, 204));
        cata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(cata);
        cata.setBounds(40, 120, 270, 20);

        brand.setBackground(new java.awt.Color(255, 255, 255));
        brand.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        brand.setForeground(new java.awt.Color(0, 0, 204));
        brand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(brand);
        brand.setBounds(360, 120, 270, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Manager  Name :");
        ppur.add(jLabel6);
        jLabel6.setBounds(360, 140, 120, 20);

        uprice.setBackground(new java.awt.Color(255, 255, 255));
        uprice.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        uprice.setForeground(new java.awt.Color(0, 0, 204));
        uprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(uprice);
        uprice.setBounds(360, 80, 270, 20);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Unit Price :");
        ppur.add(jLabel27);
        jLabel27.setBounds(360, 60, 140, 20);

        Pronaa1.setBackground(new java.awt.Color(255, 255, 255));
        Pronaa1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Pronaa1.setForeground(new java.awt.Color(0, 0, 204));
        Pronaa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(Pronaa1);
        Pronaa1.setBounds(360, 40, 270, 20);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 51));
        jLabel28.setText("Product Name :");
        ppur.add(jLabel28);
        jLabel28.setBounds(360, 20, 98, 20);

        vname.setBackground(new java.awt.Color(255, 255, 255));
        vname.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        vname.setForeground(new java.awt.Color(0, 0, 204));
        vname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(vname);
        vname.setBounds(710, 40, 260, 20);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("Vendor Name :");
        ppur.add(jLabel33);
        jLabel33.setBounds(710, 20, 120, 20);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("Quantity :");
        ppur.add(jLabel29);
        jLabel29.setBounds(710, 60, 140, 20);

        qun1.setBackground(new java.awt.Color(255, 255, 255));
        qun1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        qun1.setForeground(new java.awt.Color(0, 0, 204));
        qun1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qun1ActionPerformed(evt);
            }
        });
        ppur.add(qun1);
        qun1.setBounds(710, 80, 260, 20);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 51));
        jLabel34.setText("Date :");
        ppur.add(jLabel34);
        jLabel34.setBounds(710, 140, 40, 20);

        d5.setBackground(new java.awt.Color(255, 255, 255));
        d5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        d5.setForeground(new java.awt.Color(0, 0, 204));
        d5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(d5);
        d5.setBounds(710, 160, 120, 20);

        t5.setBackground(new java.awt.Color(255, 255, 255));
        t5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        t5.setForeground(new java.awt.Color(0, 0, 204));
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(t5);
        t5.setBounds(840, 160, 130, 20);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 51));
        jLabel30.setText("Time :");
        ppur.add(jLabel30);
        jLabel30.setBounds(840, 140, 40, 20);

        mnii.setBackground(new java.awt.Color(255, 255, 255));
        mnii.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        mnii.setForeground(new java.awt.Color(0, 0, 204));
        mnii.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(mnii);
        mnii.setBounds(40, 160, 270, 20);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("Catagory :");
        ppur.add(jLabel35);
        jLabel35.setBounds(40, 100, 110, 20);

        mnamee.setBackground(new java.awt.Color(255, 255, 255));
        mnamee.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        mnamee.setForeground(new java.awt.Color(0, 0, 204));
        mnamee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ppur.add(mnamee);
        mnamee.setBounds(360, 160, 270, 20);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 51));
        jLabel36.setText("Total :");
        ppur.add(jLabel36);
        jLabel36.setBounds(710, 100, 140, 20);

        TOTALL.setBackground(new java.awt.Color(255, 255, 255));
        TOTALL.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        TOTALL.setForeground(new java.awt.Color(0, 0, 204));
        TOTALL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TOTALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALLActionPerformed(evt);
            }
        });
        ppur.add(TOTALL);
        TOTALL.setBounds(710, 120, 260, 20);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("Brand :");
        ppur.add(jLabel37);
        jLabel37.setBounds(360, 100, 140, 20);

        jPanel1.add(ppur, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1010, 190));

        tt.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tt.setForeground(new java.awt.Color(0, 0, 204));
        tt.setText("08:20 PM");
        jPanel1.add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 106, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("TIME :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("DATE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 20));

        dd.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        dd.setForeground(new java.awt.Color(0, 0, 204));
        dd.setText("04-02-2021");
        jPanel1.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, 20));

        All.setBackground(new java.awt.Color(143, 206, 254));
        All.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2), "All Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N
        All.setLayout(null);

        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Status.setForeground(new java.awt.Color(0, 0, 204));
        Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        All.add(Status);
        Status.setBounds(40, 40, 270, 20);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 51));
        jLabel20.setText("Product ID :");
        All.add(jLabel20);
        jLabel20.setBounds(360, 70, 80, 20);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 51));
        jLabel38.setText("Price :");
        All.add(jLabel38);
        jLabel38.setBounds(40, 130, 110, 20);

        ttt1.setBackground(new java.awt.Color(255, 255, 255));
        ttt1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ttt1.setForeground(new java.awt.Color(0, 0, 204));
        ttt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(ttt1);
        ttt1.setBounds(40, 90, 270, 20);

        Pric.setBackground(new java.awt.Color(255, 255, 255));
        Pric.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Pric.setForeground(new java.awt.Color(0, 0, 204));
        Pric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(Pric);
        Pric.setBounds(40, 150, 270, 20);

        qqt.setBackground(new java.awt.Color(255, 255, 255));
        qqt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        qqt.setForeground(new java.awt.Color(0, 0, 204));
        qqt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(qqt);
        qqt.setBounds(360, 150, 270, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 51));
        jLabel8.setText("Status :");
        All.add(jLabel8);
        jLabel8.setBounds(40, 20, 120, 20);

        piid.setBackground(new java.awt.Color(255, 255, 255));
        piid.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        piid.setForeground(new java.awt.Color(0, 0, 204));
        piid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(piid);
        piid.setBounds(360, 90, 270, 20);

        vvname.setBackground(new java.awt.Color(255, 255, 255));
        vvname.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        vvname.setForeground(new java.awt.Color(0, 0, 204));
        vvname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(vvname);
        vvname.setBounds(360, 40, 270, 20);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 51));
        jLabel41.setText("Product Name :");
        All.add(jLabel41);
        jLabel41.setBounds(710, 70, 110, 20);

        ddd1.setBackground(new java.awt.Color(255, 255, 255));
        ddd1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ddd1.setForeground(new java.awt.Color(0, 0, 204));
        ddd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        All.add(ddd1);
        ddd1.setBounds(710, 40, 260, 20);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(153, 0, 51));
        jLabel42.setText("Vendor Name :");
        All.add(jLabel42);
        jLabel42.setBounds(360, 20, 120, 20);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(153, 0, 51));
        jLabel43.setText("Quantity :");
        All.add(jLabel43);
        jLabel43.setBounds(360, 130, 140, 20);

        pnnam.setBackground(new java.awt.Color(255, 255, 255));
        pnnam.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        pnnam.setForeground(new java.awt.Color(0, 0, 204));
        pnnam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnnamActionPerformed(evt);
            }
        });
        All.add(pnnam);
        pnnam.setBounds(710, 90, 260, 20);

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(153, 0, 51));
        jLabel44.setText("Date :");
        All.add(jLabel44);
        jLabel44.setBounds(710, 20, 40, 20);

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(153, 0, 51));
        jLabel45.setText("Time :");
        All.add(jLabel45);
        jLabel45.setBounds(40, 70, 40, 20);

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 0, 51));
        jLabel47.setText("Total :");
        All.add(jLabel47);
        jLabel47.setBounds(710, 130, 140, 20);

        TOTALL1.setBackground(new java.awt.Color(255, 255, 255));
        TOTALL1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        TOTALL1.setForeground(new java.awt.Color(0, 0, 204));
        TOTALL1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TOTALL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALL1ActionPerformed(evt);
            }
        });
        All.add(TOTALL1);
        TOTALL1.setBounds(710, 150, 260, 20);

        jPanel1.add(All, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1010, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1070, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     void date() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dd.setText(s.format(d));
    }

    void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                tt.setText(s.format(d));
            }
        }
        ).start();

    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
        
        
        
            if (r1.isSelected() == true){
                ssel.setVisible(false);
                ppur.setVisible(false);
                Pur.setVisible(false);
                alll.setVisible(true);
                sell.setVisible(false);
                All.setVisible(true);
                cc1();

            }else if(r2.isSelected() == true){

                ssel.setVisible(false);
                ppur.setVisible(true);
                Pur.setVisible(true);
                alll.setVisible(false);
                sell.setVisible(false);
                 All.setVisible(false);

               
                    aa1();
                

            }else if(r3.isSelected() == true){
                ssel.setVisible(true);
                ppur.setVisible(false);
                Pur.setVisible(false);
                alll.setVisible(false);
                sell.setVisible(true);
                 All.setVisible(false);
                   

                    bb2();
                
            }
        
    }//GEN-LAST:event_jButton5ActionPerformed

  public void bb2(){
         try {
        
             //Data fetch from database
            String sql = "Select * From sell where Date = '"+Dd+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
           DefaultTableModel model =(DefaultTableModel)table4.getModel(); 
           model.setRowCount(0);
           while (rs.next())
           {
               
               Object o []={
                  
                   rs.getString("Product_id"),rs.getString("Product_name"),rs.getString("Quantity"),rs.getString("Price"),
                    rs.getString("Total"),rs.getString("Profit"),rs.getString("Date"),rs.getString("Time") };
                   model.addRow(o);
             //  table2.setForeground(Color.BLUE);
               JTableHeader tableHeader = table4.getTableHeader();
               tableHeader. setBackground(Color.GREEN);
           }
            }catch(Exception e){
            System.out.println("error"+e);
        }
    }   
    public void aa1(){
        
    try {
        
             //Data fetch from database
            String sql = "Select * From purchase where DATE = '"+Dd+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
           DefaultTableModel model =(DefaultTableModel)table2.getModel(); 
           model.setRowCount(0);
           while (rs.next())
           {
               
               Object o []={
                  
                   rs.getString("PRODUCT_ID"),rs.getString("PRODUCT_NAME"),rs.getString("QUANTITY"),rs.getString("STANDERD_COST"),
                        rs.getString("TOTAL"),rs.getString("DATE"),rs.getString("TIME") };
                   model.addRow(o);
               table2.setForeground(Color.BLUE);
               JTableHeader tableHeader = table2.getTableHeader();
               tableHeader. setBackground(Color.GREEN);
           }
            }catch(Exception e){
            System.out.println("error"+e);
        }
}
    public void cc1(){
        
    try {
        
             //Data fetch from database
            String sql = "Select * From s_p_all where Date = '"+Dd+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
           DefaultTableModel model =(DefaultTableModel)table3.getModel(); 
           model.setRowCount(0);
           while (rs.next())
           {
               
               Object o []={
                  
                   rs.getString("Status"),rs.getString("Date"),rs.getString("Time"),rs.getString("Vendor_name"),rs.getString("Product_id"),
                            rs.getString("P_name"),rs.getString("Price"),rs.getString("Quantity"),rs.getString("Total") };
                   model.addRow(o);
               table3.setForeground(Color.BLUE);
               JTableHeader tableHeader = table3.getTableHeader();
               tableHeader. setBackground(Color.GREEN);
           }
            }catch(Exception e){
            System.out.println("error"+e);
        }
}
    private void pfffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfffActionPerformed

    private void ppro_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppro_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppro_id1ActionPerformed

    private void qun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qun1ActionPerformed

    private void TOTALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALLActionPerformed

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
        // TODO add your handling code here:

        int i = table4.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)table4.getModel();
        String bb=model.getValueAt(i,7).toString();
        String aa= model.getValueAt(i,6).toString();
        //System.out.println("aaa"+aa);

        try{
            String sql = "Select * from sell Where Date = ? and Time =?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,aa);
            ps.setString(2,bb);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emn=rs.getString("Employee_name");
                String dddd=rs.getString("Date");
                String tttt=rs.getString("Time");
                String ppnn=rs.getString("Product_name");
                String ppiii=rs.getString("Product_id");
                String add =rs.getString("Quantity");
                String emii=rs.getString("Emp_id");
                String too=rs.getString("Total");
                String pprii=rs.getString("Price");
                String pprof =rs.getString("Profit");
                ppro_id.setText(ppiii);
                EMPP.setText(emn);
                EMPII.setText(emii);
                d0.setText(dddd);
                t0.setText(tttt);
                QQW.setText(add);
                Paaaa.setText(ppnn);
                Taa.setText(too);
                PII.setText(pprii);
                pfff.setText(pprof);

                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE");
            }
            con.close();
        }
        catch(Exception e){System.out.println(e);
        }

    }//GEN-LAST:event_table4MouseClicked

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        int i = table2.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)table2.getModel();
        String bb=model.getValueAt(i,6).toString();
        String aa= model.getValueAt(i,5).toString();
        //System.out.println("aaa"+aa);

        try{
            String sql = "Select * from purchase Where DATE = ? and TIME =?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,aa);
            ps.setString(2,bb);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emn=rs.getString("VENDOR_NAME");
                String dddd=rs.getString("DATE");
                String tttt=rs.getString("TIME");
                String ppnn=rs.getString("PRODUCT_NAME");
                String ppiii=rs.getString("PRODUCT_ID");
                String add =rs.getString("STANDERD_COST");
                String emii=rs.getString("UNIT_PRICE");
                String too=rs.getString("QUANTITY");
                String pprii=rs.getString("CATEGORY");
                String pprof =rs.getString("BRAND");
                String mname=rs.getString("MANAGER_NAME");
                String TOTAL=rs.getString("TOTAL");
                String MNIII =rs.getString("MAN_ID");
                ppro_id1.setText(ppiii);
                vname.setText(emn);
                uprice.setText(emii);
                d5.setText(dddd);
                t5.setText(tttt);
                scost.setText(add);
                Pronaa1.setText(ppnn);
                qun1.setText(too);
                cata.setText(pprii);
                brand.setText(pprof);
                mnamee.setText(mname);
                TOTALL.setText(TOTAL);
                mnii.setText(MNIII);

                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE!!!!!!");
            }
            con.close();
        }
        catch(Exception e){System.out.println(e);
        }
    }//GEN-LAST:event_table2MouseClicked

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        String ss = search.getText();
        if(ss.equals("-: Enter Product Id :-")){
            search.setText("");
        }

    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:
        String ss = search.getText();
        if(ss.equals("")){
            search.setText("-: Enter Product Id :-");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String Search = search.getText();

        if (r1.isSelected() == true){
            ssel.setVisible(false);
            ppur.setVisible(false);
            Pur.setVisible(false);
            alll.setVisible(true);
             All.setVisible(true);
            sell.setVisible(false);

            try {

                    //Data fetch from database
                    String sql = "Select * From s_p_all Where Product_id like '%"+Search+"%' and Date = '"+Dd+"'";
                    Connection con=DATABASE_CONNECTION.getConnection();
                    PreparedStatement ps=con.prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    DefaultTableModel model =(DefaultTableModel)table3.getModel();
                    model.setRowCount(0);
                    while (rs.next())
                    {

                        Object o []={
//             
                            rs.getString("Status"),rs.getString("Date"),rs.getString("Time"),rs.getString("Vendor_name"),rs.getString("Product_id"),
                            rs.getString("P_name"),rs.getString("Price"),rs.getString("Quantity"),rs.getString("Total") };
                        model.addRow(o);
                        table3.setForeground(Color.BLUE);
                        JTableHeader tableHeader = table3.getTableHeader();
                        tableHeader. setBackground(Color.GREEN);
                    }
                }catch(Exception e){
                    System.out.println("error"+e);
                }
            
        }else if(r2.isSelected() == true){

            ssel.setVisible(false);
            ppur.setVisible(true);
            Pur.setVisible(true);
            alll.setVisible(false);
            sell.setVisible(false);
            All.setVisible(false);

           
                try {

                    //Data fetch from database
                    String sql = "Select * From purchase Where PRODUCT_ID like '%"+Search+"%' and DATE = '"+Dd+"'";
                    Connection con=DATABASE_CONNECTION.getConnection();
                    PreparedStatement ps=con.prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    DefaultTableModel model =(DefaultTableModel)table2.getModel();
                    model.setRowCount(0);
                    while (rs.next())
                    {

                        Object o []={

                            rs.getString("PRODUCT_ID"),rs.getString("PRODUCT_NAME"),rs.getString("QUANTITY"),rs.getString("STANDERD_COST"),
                            rs.getString("TOTAL"),rs.getString("DATE"),rs.getString("TIME") };
                        model.addRow(o);
                        table2.setForeground(Color.BLUE);
                        JTableHeader tableHeader = table2.getTableHeader();
                        tableHeader. setBackground(Color.GREEN);
                    }
                }catch(Exception e){
                    System.out.println("error"+e);
                }
            
              

        }else if(r3.isSelected() == true){
            ssel.setVisible(true);
            ppur.setVisible(false);
            Pur.setVisible(false);
            alll.setVisible(false);
            sell.setVisible(true);
            All.setVisible(false);
           
                try {

                    //Data fetch from database
                    String sql = "Select * From sell Where Product_id like '%"+Search+"%'and Date = '"+Dd+"'";
                    Connection con=DATABASE_CONNECTION.getConnection();
                    PreparedStatement ps=con.prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    DefaultTableModel model =(DefaultTableModel)table4.getModel();
                    model.setRowCount(0);
                    while (rs.next())
                    {

                        Object o []={

                            rs.getString("Product_id"),rs.getString("Product_name"),rs.getString("Quantity"),rs.getString("Price"),
                            rs.getString("Total"),rs.getString("Profit"),rs.getString("Date"),rs.getString("Time") };
                        model.addRow(o);
                        //  table2.setForeground(Color.BLUE);
                        JTableHeader tableHeader = table4.getTableHeader();
                        tableHeader. setBackground(Color.GREEN);
                    }
                }catch(Exception e){
                    System.out.println("error"+e);
                }
            
        }
    }//GEN-LAST:event_searchKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        search.setText("");
          if(r1.isSelected() == true){

            ssel.setVisible(false);
            ppur.setVisible(false);
            Pur.setVisible(false);
            alll.setVisible(true);
             All.setVisible(true);
            sell.setVisible(false);
                   
       cc1();
          
          }else if(r2.isSelected() == true){

            ssel.setVisible(false);
            ppur.setVisible(true);
            Pur.setVisible(true);
            alll.setVisible(false);
            sell.setVisible(false);
             All.setVisible(false);
                aa1();
            
        }else if(r3.isSelected() == true){
            ssel.setVisible(true);
            ppur.setVisible(false);
            Pur.setVisible(false);
            alll.setVisible(false);
            sell.setVisible(true);
            All.setVisible(false);

                bb2();
            
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        DASHBOARD_M dm = new DASHBOARD_M();
       dm.mngname(Name,ID,Email,Phone,date,time);
        dm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void pnnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnnamActionPerformed

    private void TOTALL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALL1ActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        // TODO add your handling code here:
         int i = table3.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)table3.getModel();
        String bb=model.getValueAt(i,1).toString();
        String aa= model.getValueAt(i,2).toString();
        //System.out.println("aaa"+aa);

        try{
            String sql = "Select * from s_p_all Where Date = ? and Time =?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,aa);
            ps.setString(2,bb);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emn=rs.getString("Status");
                String dddd=rs.getString("Date");
                String tttt=rs.getString("Time");
                String pprof =rs.getString("Vendor_name");
                String ppnn=rs.getString("P_name");
                String ppiii=rs.getString("Product_id");
                String add =rs.getString("Quantity");
               
                String too=rs.getString("Total");
                String pprii=rs.getString("Price");
                
                piid.setText(ppiii);
                Status.setText(emn);
               
                ddd1.setText(dddd);
                ttt1.setText(tttt);
                qqt.setText(add);
                pnnam.setText(ppnn);
                TOTALL1.setText(too);
                Pric.setText(pprii);
                vvname.setText(pprof);

                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE");
            }
            con.close();
        }
        catch(Exception e){System.out.println(e);
        }

                       
    }//GEN-LAST:event_table3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAILY_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAILY_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAILY_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAILY_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DAILY_REPORT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel All;
    private javax.swing.JTextField EMPII;
    private javax.swing.JTextField EMPP;
    private javax.swing.JTextField PII;
    private javax.swing.JTextField Paaaa;
    private javax.swing.JTextField Pric;
    private javax.swing.JTextField Pronaa1;
    private javax.swing.JPanel Pur;
    private javax.swing.JTextField QQW;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField TOTALL;
    private javax.swing.JTextField TOTALL1;
    private javax.swing.JTextField Taa;
    private javax.swing.JPanel alll;
    private javax.swing.JTextField brand;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cata;
    private javax.swing.JTextField d0;
    private javax.swing.JTextField d5;
    private javax.swing.JLabel dd;
    private javax.swing.JTextField ddd1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField mnamee;
    private javax.swing.JTextField mnii;
    private javax.swing.JTextField pfff;
    private javax.swing.JTextField piid;
    private javax.swing.JTextField pnnam;
    private javax.swing.JTextField ppro_id;
    private javax.swing.JTextField ppro_id1;
    private javax.swing.JPanel ppur;
    private javax.swing.JTextField qqt;
    private javax.swing.JTextField qun1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField scost;
    private javax.swing.JTextField search;
    private javax.swing.JPanel sell;
    private javax.swing.JPanel ssel;
    private javax.swing.JTextField t0;
    private javax.swing.JTextField t5;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JLabel tt;
    private javax.swing.JTextField ttt1;
    private javax.swing.JTextField uprice;
    private javax.swing.JTextField vname;
    private javax.swing.JTextField vvname;
    // End of variables declaration//GEN-END:variables
}
