/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eazy_mng;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author RAGHUNATH DAS
 */
public class FORGOT_PASSWORD extends javax.swing.JFrame {
      String otp;
     String eml;
     String phonee;
     String name;
     
     
    /**
     * Creates new form LOGIN_M
     */
    public FORGOT_PASSWORD() {
        initComponents();
        pass1.setEnabled(false);
        b.setEnabled(false);
        b2.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hide2 = new javax.swing.JLabel();
        open2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mng_id = new javax.swing.JTextField();
        b = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(154, 211, 188));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (1).png"))); // NOI18N
        hide2.setPreferredSize(new java.awt.Dimension(24, 33));
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide2MousePressed(evt);
            }
        });
        jPanel2.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 40, 60));

        open2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        open2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (2).png"))); // NOI18N
        open2.setPreferredSize(new java.awt.Dimension(24, 33));
        open2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                open2MousePressed(evt);
            }
        });
        jPanel2.add(open2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 40, 60));

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email.png"))); // NOI18N
        jLabel3.setText("Email ID / Phone");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 420, 30));

        mng_id.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel2.add(mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 420, 60));

        b.setBackground(new java.awt.Color(0, 153, 0));
        b.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("Verify Code");
        b.setBorder(null);
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });
        jPanel2.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 140, 50));

        b2.setBackground(new java.awt.Color(0, 153, 204));
        b2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b2.setText("Send");
        b2.setBorder(null);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        jPanel2.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 110, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Enter Your OTP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 420, 50));

        pass1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 420, 60));

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forgot Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 472, 496));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close3.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(558, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
       LOGINFROM dm = new LOGINFROM();
        dm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    
    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        // TODO add your handling code here:
        
        try{
          if(" ".equals(pass1.getText())){
             JOptionPane.showMessageDialog(null, "OTP Field is blank", "Error", JOptionPane.ERROR_MESSAGE); 
          }else if (pass1.getText().equals(otp)){
            JOptionPane.showMessageDialog(null, "OTP Validate Successfully");
            RESET_PASSWORD FP = new RESET_PASSWORD();
            FP.res(eml, phonee);
            FP.setVisible(true);
            this.dispose();
            }
            else{
            JOptionPane.showMessageDialog(null, "Enter Your Currect OTP", " Error", JOptionPane.ERROR_MESSAGE);   
           }
        }catch (Exception e){
            System.out.println("Exception -"+e);
        }  
        
    }//GEN-LAST:event_bMouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
        String p_email = mng_id.getText();
        String phone = mng_id.getText();
        
        try {
            //  Data fetch from database
            String sql = "Select * from register Where EMAIL =? or MOBILE_NO =? ";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,p_email);
            ps.setString(2,phone);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                eml =rs.getString("Email");
                phonee =rs.getString("MOBILE_NO");
              String  fname=rs.getString("FIRST_NAME");
             String   lname=rs.getString("LAST_NAME");
                 name=fname+" "+lname;
                System.out.println("EMAILLLLLLLL "+eml);
                System.out.println("phoooooo "+phonee);
                
                rs.close();
                ps.close();
            
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
        try{
            if(p_email.equals(eml)||phone.equals(phonee) ){
              gen_otp();
               pass1.setEnabled(true);
               b.setEnabled(true);
                b2.setEnabled(false);
               
                System.out.println("matched"+eml);    
             JOptionPane.showMessageDialog(null, "OTP Sand To"+" "+name);
            /* if(REGISTRATION_DATAOBEJECT.vali(p_email, phone)){
                gen_otp();
                JOptionPane.showMessageDialog(null, "OTP Send");
                
                
             */ 
            } else{
                    
                JOptionPane.showMessageDialog(null,"Enter Correct Email Id/ Phone Number ", "Login Error", JOptionPane.ERROR_MESSAGE);
                 pass1.setEnabled(false);
                 b.setEnabled(false);
                  b2.setEnabled(true);
            }}
        catch (Exception e){
            System.out.println("Exceptionsssss -"+e);
        }  
     
    }//GEN-LAST:event_b2MouseClicked

    private void hide2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MousePressed
        // TODO add your handling code here:
        open2.setVisible(true);
        hide2.setVisible(false);
        pass1.setEchoChar((char)0);
    }//GEN-LAST:event_hide2MousePressed

    private void open2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open2MousePressed
        // TODO add your handling code here:
        hide2.setVisible(true);
        open2.setVisible(false);
        pass1.setEchoChar('*');
    }//GEN-LAST:event_open2MousePressed

    
    public void gen_otp(){
         Random rand = new Random();
         otp = String.format("%06d",rand.nextInt(1000000));
        System.out.println("YOUR OTP IS "+otp);
       
          try{
             // String mng = eml.getText();
              String msc= "YOUR OTP IS "+otp;
            MAIL.send(eml,"Welcome"+" "+name, msc);
            
            
                   

        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORGOT_PASSWORD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton b2;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mng_id;
    private javax.swing.JLabel open2;
    private javax.swing.JPasswordField pass1;
    // End of variables declaration//GEN-END:variables
}
