package eazy_mng;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAGHUNATH DAS
 */


public class FORGOT_PASSWORD_EMP1 extends javax.swing.JFrame {
    String phone;
    String email;
    /**
     * Creates new form FORGOT_PASSWORD
     */
    public FORGOT_PASSWORD_EMP1() {
        initComponents();
        p3.setVisible(false);
        p4.setVisible(false);
        p1.setEchoChar((char)0);
        p2.setEchoChar((char)0);
    }
void res (String eml, String mob) {
        email= eml;
        phone  = mob;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        h = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        cl = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p3.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        p3.setForeground(new java.awt.Color(102, 0, 153));
        p3.setText("Enter New Password :");
        jPanel2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, 30));

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("RESET");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 40));

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));
        jLabel5.setText("PASSWORD !");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, 40));

        p4.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        p4.setForeground(new java.awt.Color(102, 0, 153));
        p4.setText("Confirm New Password :");
        jPanel2.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rrrr.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reset");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 100, 40));

        p2.setBackground(new java.awt.Color(0, 204, 204));
        p2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(102, 0, 153));
        p2.setText("Confirm New Password :");
        p2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        p2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                p2FocusLost(evt);
            }
        });
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 330, 30));

        p1.setBackground(new java.awt.Color(0, 204, 204));
        p1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(102, 0, 153));
        p1.setText("Enter New Password :");
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        p1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                p1FocusLost(evt);
            }
        });
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 330, 40));

        h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide00.png"))); // NOI18N
        h.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hMouseClicked(evt);
            }
        });
        jPanel2.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 30, 30));

        o.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view00.png"))); // NOI18N
        o.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oMouseClicked(evt);
            }
        });
        jPanel2.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 30, 30));

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide00.png"))); // NOI18N
        h2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        h2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h2MouseClicked(evt);
            }
        });
        jPanel2.add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 30, 30));

        o2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view00.png"))); // NOI18N
        o2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 0, 153)));
        o2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o2MouseClicked(evt);
            }
        });
        jPanel2.add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 870, 480));

        cl.setBackground(new java.awt.Color(255, 51, 102));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close (1).png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout clLayout = new javax.swing.GroupLayout(cl);
        cl.setLayout(clLayout);
        clLayout.setHorizontalGroup(
            clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        clLayout.setVerticalGroup(
            clLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(980, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private static final String A ="^(?:(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|" +
			"(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|" +
			"(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|" +
			"(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))(?!.*(.)\\1{2,})" +
			"[A-Za-z0-9!~<>,;:_=?*+#.\"&§%°()\\|\\[\\]\\-\\$\\^\\@\\/]" +
			"{8,30}$";
    private static final Pattern PASSWORD_PATTERN = Pattern.compile(A);
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:

        new LOGIN_EMPLOYEE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        cl.setBackground(Color.red);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        cl.setBackground( new Color(255,51,102));

    }//GEN-LAST:event_jLabel18MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        String Paass = p1.getText();      
        String Paaas = p2.getText();
       
        //(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NO,PASSWORD,CONFIRM_PASSWORD,ADDRESS,GENDER)
       //  if(PASSWORD_PATTERN.matcher(Paass).matches()){  
        
        if(Paass.equals(Paaas)){
               UPDATEPROFILE_M_DATAOBJECT.Reset_password2(Paass, Paaas,email);
                System.out.println("Data inserted");
               
               
                JOptionPane.showMessageDialog(this, "Your Password Change Sucessfully "); 
                new LOGINFROM().setVisible(true);
                this.dispose();
           }else{
                System.out.println("Data NOT inserted");
                JOptionPane.showMessageDialog(this, "Both Password Not Same"); 
           }
      //   }
//         else {
//               JOptionPane.showMessageDialog(null, "Password between 8 and 30 characters\nPassword must contain at least one lowercase letter\none uppercase letter\none numeric digit\none special character.");
//         }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked
        // TODO add your handling code here:
        o.setVisible(true);
        h.setVisible(false);
        p1.setEchoChar((char)0);
    }//GEN-LAST:event_hMouseClicked

    private void oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseClicked
        // TODO add your handling code here:
        h.setVisible(true);
        o.setVisible(false);
        p1.setEchoChar('*');
    }//GEN-LAST:event_oMouseClicked

    private void h2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h2MouseClicked
        // TODO add your handling code here:
        o2.setVisible(true);
        h2.setVisible(false);
        p2.setEchoChar((char)0);
    }//GEN-LAST:event_h2MouseClicked

    private void o2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o2MouseClicked
        // TODO add your handling code here:
         h2.setVisible(true);
        o2.setVisible(false);
        p2.setEchoChar('*');
    }//GEN-LAST:event_o2MouseClicked

    private void p1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p1FocusGained
        // TODO add your handling code here:
        if(p1.getText().equals("Enter New Password :")){
            p3.setVisible(true);
             p1.setText("");
             p1.setEchoChar('*');
        }
    }//GEN-LAST:event_p1FocusGained

    private void p1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p1FocusLost
        // TODO add your handling code here:
        
        if(p1.getText().equals("")){
            p3.setVisible(false);
            p1.setText("Enter New Password :");
            p1.setEchoChar((char)0);
            
        }
    }//GEN-LAST:event_p1FocusLost

    private void p2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2FocusGained
        // TODO add your handling code here:
        
         if(p2.getText().equals("Confirm New Password :")){
            p4.setVisible(true);
             p2.setText("");
             p2.setEchoChar('*');
        }
    }//GEN-LAST:event_p2FocusGained

    private void p2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2FocusLost
        // TODO add your handling code here:
        if(p2.getText().equals("")){
            p4.setVisible(false);
            p2.setText("Confirm New Password :");
            p2.setEchoChar((char)0);
            
        }
    }//GEN-LAST:event_p2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD_EMP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD_EMP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD_EMP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORGOT_PASSWORD_EMP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORGOT_PASSWORD_EMP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cl;
    private javax.swing.JLabel h;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel o;
    private javax.swing.JLabel o2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    // End of variables declaration//GEN-END:variables
}
