/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eazy_mng;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sudip Maiti
 */
public class GIVE_ATTEDENCE extends javax.swing.JFrame {

    String ID = null;
    String Name = null;
    String Phone = null;
    String Email = null;
    String DOB = null;
    String Gender= null;
    String Address =null;
    String date=null;
    String time = null;
    
    /**
     * Creates new form REMOVE_EMPLOYEE
     */
    public GIVE_ATTEDENCE() {
        initComponents();
        date();
        time();
        
    }

    void gaa (String fullname, String mng_Id,String email,String t1,String d1,String p) {
       Name = fullname;
        ID = mng_Id;
        Email = email;
        time = t1;
        date = d1;
        Phone= p;
        
        ab.setText(Name);
        ab.setEditable(false);
        dd.setText(date);
        dd.setEditable(false);
        mng_id.setText(ID);
        mng_id.setEditable(false);
    }
    
    
    
    public void enable()
    {
       if("".equals(in_t.getText())) {
           update.setEnabled(false);
           save.setEnabled(true);
           System.out.println("intimmmmm"+in_t.getText());
           
       }else if(!"".equals(in_t.getText()) ){
        update.setEnabled(true);
        save.setEnabled(false);
         System.out.println("intinnnnnnnn"+in_t.getText());
    }
       
    }
    
    
    
    
    
    public void table()
{
    String empee= emp.getText();
    try {
        
             //Data fetch from database
            String sql = "Select * From attendance where EMP_ID='"+empee+"' ";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            
           DefaultTableModel model =(DefaultTableModel)table.getModel(); 
           model.setRowCount(0);
           while (rs.next())
           {
               
               Object o []={
                   rs.getString("EMP_ID"),rs.getString("EMP_NAME"),rs.getString("ATTENDANCE_BY"),rs.getString("MNG_ID"),rs.getString("IN_TIME"),
              rs.getString("OUT_TIME"),rs.getString("BREAK_TIME"),rs.getString("DATE"),rs.getString("STATUS") };
               model.addRow(o);
               
           }
            }catch(Exception e){
            System.out.println("error"+e);
        }
}
    
    void date() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEE-dd-MMMM-yyyy");
        daaa.setText(s.format(d));
    }
    

    void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                tii.setText(s.format(d));
            }
        }
        ).start();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        emp = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        tii = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        daaa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        in_t = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        en = new javax.swing.JTextField();
        ab = new javax.swing.JTextField();
        dd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        o_t = new javax.swing.JTextField();
        b_t = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sta = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mng_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATTEDENCE ");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        jPanel3.setBackground(new java.awt.Color(210, 169, 251));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp.setBackground(new java.awt.Color(255, 255, 255));
        emp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        emp.setForeground(new java.awt.Color(0, 0, 255));
        emp.setText("Enter Employee ID");
        emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emp.setMargin(new java.awt.Insets(10, 10, 10, 10));
        emp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFocusLost(evt);
            }
        });
        jPanel3.add(emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 30));

        save.setBackground(new java.awt.Color(255, 255, 0));
        save.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 255));
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 160, 30));

        tii.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tii.setForeground(new java.awt.Color(204, 0, 204));
        tii.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 255)));
        jPanel3.add(tii, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 230, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Attedence By :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 90, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("All Details");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 30));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        table.setForeground(new java.awt.Color(0, 0, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp Id", "Name", "Attedence By", "Mng_ID", "In Time", "Out Time", "Break Time", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 730, 180));

        daaa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        daaa.setForeground(new java.awt.Color(204, 0, 204));
        daaa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 255)));
        jPanel3.add(daaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Date :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        in_t.setBackground(new java.awt.Color(255, 255, 255));
        in_t.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        in_t.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(in_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Name :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, -1));

        jButton7.setBackground(new java.awt.Color(0, 224, 201));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 204));
        jButton7.setText("Search");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Date :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 90, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Status:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 90, -1));

        en.setBackground(new java.awt.Color(255, 255, 255));
        en.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        en.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(en, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 30));

        ab.setBackground(new java.awt.Color(255, 255, 255));
        ab.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 30));

        dd.setBackground(new java.awt.Color(255, 255, 255));
        dd.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Out Time :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 90, -1));

        o_t.setBackground(new java.awt.Color(255, 255, 255));
        o_t.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        o_t.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(o_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 30));

        b_t.setBackground(new java.awt.Color(255, 255, 255));
        b_t.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        b_t.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(b_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Break Time :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 90, -1));

        sta.setBackground(new java.awt.Color(255, 255, 255));
        sta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        sta.setForeground(new java.awt.Color(0, 0, 0));
        sta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Half Day", "Absent", " " }));
        jPanel3.add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 160, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("In Time :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Time :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 20));

        mng_id.setBackground(new java.awt.Color(255, 255, 255));
        mng_id.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mng_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Manager Id :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Reset");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 30));

        update.setBackground(new java.awt.Color(0, 255, 51));
        update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 255));
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(770, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        DASHBOARD_M dm = new DASHBOARD_M();
       dm.mngname(Name,ID,Email,Phone,date,time);
       dm.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        reset();
        String em_id=emp.getText();
        String datttt=dd.getText();
         try {
            String sql1 = "Select * From attendance Where EMP_ID = ? and DATE = ? ";
            Connection con1=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps1=con1.prepareStatement(sql1);
            ps1.setString(1,em_id);
            ps1.setString(2,datttt);
            ResultSet rs1=ps1.executeQuery();
            if(rs1.next()){   
                String nnn =rs1.getString("EMP_NAME");
                String in_timee =rs1.getString("IN_TIME");
                String out_timee =rs1.getString("OUT_TIME");
                String break_timee =rs1.getString("BREAK_TIME");
                String Status =rs1.getString("STATUS");
                en.setText(nnn);
                en.setEditable(false);
                in_t.setText(in_timee);
                
                o_t.setText(out_timee);
               // o_t.setEditable(false);
                b_t.setText(break_timee);
               // b_t.setEditable(false);
                sta.setSelectedItem(Status);
              //  sta.setEditable(false);
                if(in_t.equals(""))
                {
                    in_t.setEditable(true);
                }else
                    in_t.setEditable(false);
              //  in_t.setEditable(false);
                table();
                enable();                
                rs1.close();
                ps1.close();
            }else{
                
                System.out.println("Nothing Found In this ID");
            
             //Data fetch from database
            String sql = "Select * From employee_register Where EMP_ID = ?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,em_id);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emp_id =rs.getString("EMP_ID");
                String f_name =rs.getString("FIRST_NAME");
                 System.out.println("EMpppppp "+f_name);
                String l_name =rs.getString("LAST_NAME");
                 System.out.println("pppnnn "+l_name);
               String nnn=f_name+l_name;
               
                en.setText(nnn);
                en.setEditable(false);
                table();
                enable();
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(this, "Enter Correct Empolyee Id");
               // System.out.println("Enter Correct Employee Id");
            }}
        }catch(Exception e){
            System.out.println("error"+e);
        }
//        try{
//            
//            if(UPDATEPROFILE_M_DATAOBJECT.validate(em_id))
//            {System.out.println("EmpppppppppppIDD"+em_id);
//                JOptionPane.showMessageDialog(this, "Employee Found in This Id");
//           }else 
//            JOptionPane.showMessageDialog(this, "Employee ID not found");
//             
//        }catch (Exception e){
//            System.out.println("Exception -"+e);  
//    } 
//        
//        
    }//GEN-LAST:event_jButton7MouseClicked

    public void reset(){
        
        en.setText("");
        in_t.setText("");
        o_t.setText("");
        b_t.setText("");        
        DefaultTableModel tm=(DefaultTableModel) table.getModel();
        while(tm.getRowCount()>0){
            tm.setRowCount(0);
        }
        
    }
    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        
        String empe=emp.getText();
        String namee=en.getText();
        String mngg=ab.getText();
        String mngii=mng_id.getText();
        String in_time=in_t.getText();
        String out_time=o_t.getText();
        String break_t=b_t.getText();
        String Datee=dd.getText();
        String status=sta.getSelectedItem().toString();
        
         if(empe.isEmpty() || in_time.isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill Up In Time First");
        }
        else {
            
//             DefaultTableModel model = (DefaultTableModel)table.getModel();
//              model.addRow(new Object[]{p_id.getText(), p_name.getText(),desc.getText(),s_cost.getText(),unit_pri.getText(),
//                                  mfg.getText(),exp.getText(),quantity.getText(),catagory.getText(),brand.getText(),total.getText()
//              });
        int i = ATTEDENCE_DATAOBJ.atten(empe, namee, mngg, mngii, in_time, out_time, break_t, Datee, status);
        
        
        if(i>0){
            table();
        System.out.println("Data inserted");
        JOptionPane.showMessageDialog(this, "Attedence Successfully");
               }
        else{
        System.out.println("Data NOT inserted");
        JOptionPane.showMessageDialog(this, "Attedence not done");
            }
        }
    
    }//GEN-LAST:event_saveMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:\
         in_t.setEditable(false);
        String empe = emp.getText();  
        System.out.println("emppp"+empe);
        String out_t = o_t.getText();
        System.out.println("outttttt"+out_t);
        String br_t = b_t.getText();
        System.out.println("breeeeeeak"+br_t);
        String staa = sta.getSelectedItem().toString();
        System.out.println("staaaaa"+staa);
        String daaaa = dd.getText();
        System.out.println("dateeeee"+daaaa);
       
        
        int i = ATTEDENCE_DATAOBJ.update( out_t, br_t, staa,empe,daaaa);
            //(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NO,PASSWORD,CONFIRM_PASSWORD,ADDRESS,GENDER)
           if(i>0){
                System.out.println("Data inserted");
                JOptionPane.showMessageDialog(this, "Attedence Update Sucessfully "); 
                table();
           }else{
                System.out.println("Data NOT inserted");
                JOptionPane.showMessageDialog(this, "Unable to Given Attedence"); 
           }
    }//GEN-LAST:event_updateMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        emp.setText("Enter Employee ID");
        reset();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void empFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFocusGained
        // TODO add your handling code here:
       // emp.setText("");
        if(emp.getText().equals("Enter Employee ID")){
            
            emp.setText("");
           
        }
    }//GEN-LAST:event_empFocusGained

    private void empFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFocusLost
        // TODO add your handling code here:
      // emp.setText("Enter Employee ID");
       if(emp.getText().equals("")){
           
            emp.setText("Enter Employee ID");
           
        }else{
           emp.setVisible(true);
    }//GEN-LAST:event_empFocusLost
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHECK_ATTEDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHECK_ATTEDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHECK_ATTEDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHECK_ATTEDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIVE_ATTEDENCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ab;
    private javax.swing.JTextField b_t;
    private javax.swing.JLabel daaa;
    private javax.swing.JTextField dd;
    private javax.swing.JTextField emp;
    private javax.swing.JTextField en;
    private javax.swing.JTextField in_t;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mng_id;
    private javax.swing.JTextField o_t;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> sta;
    private javax.swing.JTable table;
    private javax.swing.JLabel tii;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
