/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eazy_mng;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.math.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.Timer;
/**
 *
 * @author Sudip Maiti
 */
public class MNG_REGISTER extends javax.swing.JFrame {

    String emp_id =null;
    String Mng_Id = null;
    String Name = null;
    String ID = null;
    String date=null;
    String time = null;
    String td= time+date;
    BigInteger mng_id =null;
    String mng ;
    String Transaction_Id = null;
    String pro_Id=null;
    String add =null;
    String dob=null;
    /**
     * Creates new form REGISTRATION
     */
    public MNG_REGISTER() {
        initComponents();
        
        
       //jPanel2.setBackground(new Color(255,255,255,125));
        fName.setVisible(false);
        L_name.setVisible(false);
        Phone.setVisible(false);
        Email.setVisible(false);
        Password.setVisible(false);
        CPassword.setVisible(false);
        pass.setEchoChar((char)0);
        conf_pass.setEchoChar((char)0);
//        mng_name.setEditable(false);
//        mng_id.setEditable(false);
        open.setVisible(false);
        id_create();
        date();
        time();
    }
  
    
    void date (){
      Date d=new Date ();
      SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
      date=(s.format(d));     
      
  }
  void time(){
     new Timer(0,new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e) {
            Date d=new Date ();
            SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
            time=(s.format(d));              
         }
     }).start();
      
  }
    //FETCH LAST ID FROM DATABASE AND STORE THE DATA IN GLOBAL VARIABLE
    
    void id_create(){
        Mng_id.setEditable(false);
         try{
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement("select * from id_store");         
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                Mng_Id=rs.getString("MNG_ID");
                System.out.println("MANAGER ID "+Mng_Id);
                emp_id=rs.getString("EMP_ID");
                System.out.println("EMPLOYEE ID "+emp_id);
                Transaction_Id=rs.getString("TRANSACTION_ID");
                System.out.println("Transaction_Id "+Transaction_Id);
                pro_Id=rs.getString("PRODUCT_ID");
                 System.out.println("Product_Id "+pro_Id);
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE!!!!!!");
            }
            con.close();
           }
        catch(Exception e){System.out.println(e);}
        
        mng_id = new BigInteger(Mng_Id);
        BigInteger nxt = new BigInteger("1");
        System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!"+Mng_Id);
        System.out.println("#################"+mng_id);
        mng_id = mng_id.add(nxt);
        System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+mng_id);
        mng = "INVM"+mng_id.toString();
        System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+mng);
        System.out.println("++++++++++++++++"+mng_id);
        Mng_id.setText(mng);
    }
    private static final String A ="^(?:(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|" +
			"(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|" +
			"(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|" +
			"(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))(?!.*(.)\\1{2,})" +
			"[A-Za-z0-9!~<>,;:_=?*+#.\"&§%°()\\|\\[\\]\\-\\$\\^\\@\\/]" +
			"{8,30}$";
    private static final Pattern PASSWORD_PATTERN = Pattern.compile(A);
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CPassword = new javax.swing.JLabel();
        fName = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        crt_emp = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        L_name = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone3 = new javax.swing.JTextField();
        Mng_id = new javax.swing.JTextField();
        Close = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        conf_pass = new javax.swing.JPasswordField();
        Close1 = new javax.swing.JLabel();
        open1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c2 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Close_bb = new javax.swing.JPanel();
        Close_b = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome !");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 230, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Sing Up!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 30));

        CPassword.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        CPassword.setForeground(new java.awt.Color(0, 153, 204));
        CPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPassword.setText("Confirm Password");
        jPanel2.add(CPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, 20));

        fName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        fName.setForeground(new java.awt.Color(0, 153, 204));
        fName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fName.setText("First Name");
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 20));

        Phone.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Phone.setForeground(new java.awt.Color(0, 153, 204));
        Phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Phone.setText("Phone");
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 20));

        Email.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 153, 204));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 250, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Gender");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 230, 30));

        crt_emp.setBackground(new java.awt.Color(0, 153, 204));
        crt_emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel28.setBackground(new java.awt.Color(0, 153, 204));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Create Manager");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crt_empLayout = new javax.swing.GroupLayout(crt_emp);
        crt_emp.setLayout(crt_empLayout);
        crt_empLayout.setHorizontalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        crt_empLayout.setVerticalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(crt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 250, 50));

        L_name.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        L_name.setForeground(new java.awt.Color(0, 153, 204));
        L_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_name.setText("Last Name");
        jPanel2.add(L_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 190, 20));

        Password.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 153, 204));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Password.setText("Password");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Manager ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 20));

        firstname.setBackground(new java.awt.Color(255, 255, 255));
        firstname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(0, 153, 204));
        firstname.setText("First Name");
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, 30));

        lastname.setBackground(new java.awt.Color(255, 255, 255));
        lastname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(0, 153, 204));
        lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastname.setText("Last Name");
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 250, 30));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 153, 204));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 250, 30));

        phone3.setBackground(new java.awt.Color(255, 255, 255));
        phone3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phone3.setForeground(new java.awt.Color(0, 153, 204));
        phone3.setText("Phone");
        phone3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        phone3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone3FocusLost(evt);
            }
        });
        phone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone3KeyTyped(evt);
            }
        });
        jPanel2.add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        Mng_id.setBackground(new java.awt.Color(255, 255, 255));
        Mng_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Mng_id.setForeground(new java.awt.Color(0, 153, 204));
        Mng_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Mng_id.setText("123456798");
        Mng_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Mng_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mng_idActionPerformed(evt);
            }
        });
        jPanel2.add(Mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 240, 30));

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility1.png"))); // NOI18N
        Close.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Close.setMaximumSize(new java.awt.Dimension(20, 20));
        Close.setMinimumSize(new java.awt.Dimension(20, 20));
        Close.setPreferredSize(new java.awt.Dimension(20, 20));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });
        jPanel2.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 30, 30));

        open.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (3).png"))); // NOI18N
        open.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        open.setMaximumSize(new java.awt.Dimension(20, 20));
        open.setMinimumSize(new java.awt.Dimension(20, 20));
        open.setPreferredSize(new java.awt.Dimension(20, 20));
        open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openMousePressed(evt);
            }
        });
        jPanel2.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 30, 30));

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 153, 204));
        pass.setText("Password");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox1.setToolTipText("Gender");
        jComboBox1.setLightWeightPopupEnabled(false);
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 250, -1));

        conf_pass.setBackground(new java.awt.Color(255, 255, 255));
        conf_pass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        conf_pass.setForeground(new java.awt.Color(0, 153, 204));
        conf_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        conf_pass.setText("Confirm Password");
        conf_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        conf_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conf_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                conf_passFocusLost(evt);
            }
        });
        conf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_passActionPerformed(evt);
            }
        });
        jPanel2.add(conf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 220, 30));

        Close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility1.png"))); // NOI18N
        Close1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Close1.setMaximumSize(new java.awt.Dimension(20, 20));
        Close1.setMinimumSize(new java.awt.Dimension(20, 20));
        Close1.setPreferredSize(new java.awt.Dimension(20, 20));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Close1MousePressed(evt);
            }
        });
        jPanel2.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 30, 30));

        open1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        open1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (3).png"))); // NOI18N
        open1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        open1.setMaximumSize(new java.awt.Dimension(20, 20));
        open1.setMinimumSize(new java.awt.Dimension(20, 20));
        open1.setPreferredSize(new java.awt.Dimension(20, 20));
        open1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                open1MousePressed(evt);
            }
        });
        jPanel2.add(open1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 30, 30));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(14, 73, 181));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Terms Privacy        Fees.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 414, 150, 20));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        c2.setForeground(new java.awt.Color(12, 35, 25));
        c2.setText(" I agree to the           ,              and ");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 240, 30));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        c1.setForeground(new java.awt.Color(12, 35, 25));
        c1.setText("Yes, I want to receive  emails");
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Log in.");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 50, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(10, 36, 25));
        jLabel7.setText("Already have an account ? ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 520));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("<Html>EAZY MANAGE</Html>");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 300, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/At the office-amico (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 350, 260));

        Close_bb.setBackground(new java.awt.Color(0, 153, 204));

        Close_b.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        Close_b.setForeground(new java.awt.Color(255, 255, 255));
        Close_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_b.setText("×");
        Close_b.setPreferredSize(new java.awt.Dimension(40, 40));
        Close_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_bMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Close_bbLayout = new javax.swing.GroupLayout(Close_bb);
        Close_bb.setLayout(Close_bbLayout);
        Close_bbLayout.setHorizontalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Close_bbLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Close_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Close_bbLayout.setVerticalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Close_bbLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Close_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(Close_bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(941, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseEntered
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(228, 0, 23));
         Close_b.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Close_bMouseEntered

    private void Close_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseExited
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(0,153,204));
        Close_b.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Close_bMouseExited

    private void Close_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseClicked
        // TODO add your handling code here:
        LOGINFROM ap = new LOGINFROM();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Close_bMouseClicked

    private void open1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open1MousePressed
        // TODO add your handling code here:
        open1.setVisible(false);
        Close1.setVisible(true);
        conf_pass.setEchoChar('*');
    }//GEN-LAST:event_open1MousePressed

    private void Close1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MousePressed
        // TODO add your handling code here:
        Close1.setVisible(false);
        open1.setVisible(true);
        conf_pass.setEchoChar((char)0);
    }//GEN-LAST:event_Close1MousePressed

    private void Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Close1MouseClicked

    private void conf_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conf_passFocusLost
        // TODO add your handling code here:
        if(conf_pass.getText().equals("")){
            CPassword.setVisible(false);
            conf_pass.setText("Confirm Password");
            conf_pass.setEchoChar((char)0);
            conf_pass.setForeground(new Color(0,153,204));
        }else{
            conf_pass.setVisible(true);
        }
    }//GEN-LAST:event_conf_passFocusLost

    private void conf_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conf_passFocusGained
        // TODO add your handling code here:
        if(conf_pass.getText().equals("Confirm Password")){
            CPassword.setVisible(true);
            conf_pass.setText("");
            conf_pass.setEchoChar('*');
            conf_pass.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_conf_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
        if(pass.getText().equals("")){
            Password.setVisible(false);
            pass.setText("Password");
            pass.setEchoChar((char)0);
            pass.setForeground(new Color(0,153,204));
        }else{
            pass.setVisible(true);
        }
    }//GEN-LAST:event_passFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
        if(pass.getText().equals("Password")){
            Password.setVisible(true);
            pass.setText("");
            pass.setEchoChar('*');
            pass.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_passFocusGained

    private void openMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMousePressed
        // TODO add your handling code here:
        open.setVisible(false);
        Close.setVisible(true);
        pass.setEchoChar('*');
    }//GEN-LAST:event_openMousePressed

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // TODO add your handling code here:
        Close.setVisible(false);
        open.setVisible(true);
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_CloseMousePressed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void Mng_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mng_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mng_idActionPerformed

    private void phone3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusLost
        // TODO add your handling code here:
        if(phone3.getText().equals("")){
            Phone.setVisible(false);
            phone3.setText("Phone");
            phone3.setForeground(new Color(0,153,204));
        }else{
            Phone.setVisible(true);
        }
    }//GEN-LAST:event_phone3FocusLost

    private void phone3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusGained
        // TODO add your handling code here:
        if(phone3.getText().equals("Phone")){
            Phone.setVisible(true);
            phone3.setText("");
            phone3.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_phone3FocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            Email.setVisible(false);
            email.setText("Email");
            email.setForeground(new Color(0,153,204));
        }else{
            Email.setVisible(true);
        }
    }//GEN-LAST:event_emailFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
            Email.setVisible(true);
            email.setText("");
            email.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_emailFocusGained

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        // TODO add your handling code here:
        if(lastname.getText().equals("")){
            L_name.setVisible(false);
            lastname.setText("Last Name");
            lastname.setForeground(new Color(0,153,204));
        }else{
            L_name.setVisible(true);
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        // TODO add your handling code here:
        if(lastname.getText().equals("Last Name")){
            L_name.setVisible(true);
            lastname.setText("");
            lastname.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        // TODO add your handling code here:
        if(firstname.getText().equals("")){
            fName.setVisible(false);
            firstname.setText("First Name");
            firstname.setForeground(new Color(0,153,204));
        }else{
            fName.setVisible(true);
        }
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:
        if(firstname.getText().equals("First Name")){
            fName.setVisible(true);
            firstname.setText("");
            firstname.setForeground(new Color(0,153,204));
        }

    }//GEN-LAST:event_firstnameFocusGained

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        String fName = firstname.getText();
        String lName = lastname.getText();
        String ph = phone3.getText();
        String mail = email.getText();
        String password = pass.getText();
        String c_pass = conf_pass.getText();
        
        String gen = jComboBox1.getSelectedItem().toString() ;
         if(fName.isEmpty() || lName.equals("") || ph.equals("") || mail.isEmpty() || password.equals("")|| c_pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill up all field first");
        }else if(PASSWORD_PATTERN.matcher(password).matches()){
              if(password.equals(c_pass) ){
              if(c1.isSelected()==true && c2.isSelected()==true ){
                int i = REGISTRATION_DATAOBEJECT.inventory_management_system(fName, lName,mail,ph,mng, password, c_pass,add,gen,td,dob);
                int j = ID_STORE_FETCH.insert_id(mng_id.toString(), emp_id,Transaction_Id,pro_Id);
              if(i>0 && j>0){
                System.out.println("Data inserted");
                JOptionPane.showMessageDialog(this, "Your Account Sucessfully Created"); 
                new LOGINFROM().setVisible(true);
                this.dispose();
              }else{
                System.out.println("Data NOT inserted");
                JOptionPane.showMessageDialog(this, "Your Account Not Created"); 
                    }
             }else{
                JOptionPane.showMessageDialog(this, "You have to accept our company Terms & Condition"); 
             }   
             }else {
               JOptionPane.showMessageDialog(this, "Both Password Not Same");
             }
             }else {
               JOptionPane.showMessageDialog(null, "Password between 8 and 20 characters\nPassword must contain at least one lowercase letter\none uppercase letter\none numeric digit\none special character.");
        
        }
        
                          
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void phone3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone3KeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<= '9'){
          phone3.setEditable(true);
      }else if(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar()== '+' || evt.getKeyChar()==KeyEvent.VK_SPACE)
      {
          phone3.setEditable(true);
      }
      else {
          phone3.setEditable(false);
          JOptionPane.showMessageDialog(this, "Enter Only Number Value");
      }
         
    }//GEN-LAST:event_phone3KeyTyped

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        LOGINFROM ap = new LOGINFROM();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void conf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_passActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MNG_REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MNG_REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MNG_REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MNG_REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MNG_REGISTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPassword;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close_b;
    private javax.swing.JPanel Close_bb;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel L_name;
    private javax.swing.JTextField Mng_id;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JPasswordField conf_pass;
    private javax.swing.JPanel crt_emp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel open;
    private javax.swing.JLabel open1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone3;
    // End of variables declaration//GEN-END:variables
}
